name: ci

on:
  push:
    paths:
      - "**.f"
      - "**.py"
      - ".github/workflows/ci.yml"
      - "**/meson.build"
      - "**/CMakeLists.txt"
  pull_request:
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  core:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.14']
        include:
        - os: ubuntu-latest
          python-version: '3.10'

    steps:
    - uses: msys2/setup-msys2@v2
      if: runner.os == 'Windows'
      id: msys2
      with:
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      if: runner.os == 'Windows'
      shell: bash
      run: echo "${{ steps.msys2.outputs.msys2-location }}/ucrt64/bin" >> $GITHUB_PATH

    - name: macOS Gfortran
      if: runner.os == 'macOS'
      run: echo "FC=gfortran-14" >> $GITHUB_ENV

    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Python package Meson build
      run: pip install .[tests]

    - name: Type annotation checks
      run: mypy

    - name: Python package self-tests
      run: pytest

    - name: non-Python, standalone CMake build and test
      run: cmake --workflow default
